services:

    command.state.create:
        class: eTraxis\SimpleBus\States\Handler\CreateStateCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\States\CreateStateCommand }]
        arguments: [ "@logger", "@validator", "@doctrine" ]

    command.state.update:
        class: eTraxis\SimpleBus\States\Handler\UpdateStateCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\States\UpdateStateCommand }]
        arguments: [ "@logger", "@validator", "@doctrine" ]

    command.state.delete:
        class: eTraxis\SimpleBus\States\Handler\DeleteStateCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\States\DeleteStateCommand }]
        arguments: [ "@logger", "@doctrine", "@security.authorization_checker" ]

    command.state.set_initial:
        class: eTraxis\SimpleBus\States\Handler\SetInitialStateCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\States\SetInitialStateCommand }]
        arguments: [ "@logger", "@doctrine" ]

    command.state.add_transitions:
        class: eTraxis\SimpleBus\States\Handler\AddRemoveStateTransitionsCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\States\AddStateTransitionsCommand }]
        arguments: [ "@logger", "@doctrine" ]

    command.state.remove_transitions:
        class: eTraxis\SimpleBus\States\Handler\AddRemoveStateTransitionsCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\States\RemoveStateTransitionsCommand }]
        arguments: [ "@logger", "@doctrine" ]

    command.state.add_assignees:
        class: eTraxis\SimpleBus\States\Handler\AddRemoveStateAssigneesCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\States\AddStateAssigneesCommand }]
        arguments: [ "@logger", "@doctrine" ]

    command.state.remove_assignees:
        class: eTraxis\SimpleBus\States\Handler\AddRemoveStateAssigneesCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\States\RemoveStateAssigneesCommand }]
        arguments: [ "@logger", "@doctrine" ]
