services:

    middleware.validation:
        class: eTraxis\SimpleBus\Middleware\ValidationMiddleware
        public: false
        tags: [{ name: command_bus_middleware }]
        arguments: [ @logger, @validator ]
