services:

    command.user.register:
        class: eTraxis\SimpleBus\Users\Handler\RegisterUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\RegisterUserCommand }]
        arguments: [ @logger, @doctrine, %locale%, %theme% ]

    command.user.lock:
        class: eTraxis\SimpleBus\Users\Handler\LockUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\LockUserCommand }]
        arguments: [ @logger, @doctrine, %security_auth_attempts%, %security_lock_time% ]

    command.user.unlock:
        class: eTraxis\SimpleBus\Users\Handler\UnlockUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\UnlockUserCommand }]
        arguments: [ @doctrine ]

    command.users.list:
        class: eTraxis\SimpleBus\Users\Handler\ListUsersCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\ListUsersCommand }]
        arguments: [ @translator, @doctrine ]

    command.user.find:
        class: eTraxis\SimpleBus\Users\Handler\FindUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\FindUserCommand }]
        arguments: [ @doctrine ]

    command.user.create:
        class: eTraxis\SimpleBus\Users\Handler\CreateUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\CreateUserCommand }]
        arguments: [ @logger, @validator, @translator, @doctrine, @etraxis.encoder, %locale%, %theme% ]

    command.user.update:
        class: eTraxis\SimpleBus\Users\Handler\UpdateUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\UpdateUserCommand }]
        arguments: [ @logger, @validator, @translator, @doctrine, @security.token_storage ]

    command.user.delete:
        class: eTraxis\SimpleBus\Users\Handler\DeleteUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\DeleteUserCommand }]
        arguments: [ @doctrine, @security.authorization_checker ]

    command.users.disable:
        class: eTraxis\SimpleBus\Users\Handler\DisableUsersCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\DisableUsersCommand }]
        arguments: [ @doctrine, @security.token_storage ]

    command.users.enable:
        class: eTraxis\SimpleBus\Users\Handler\EnableUsersCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\EnableUsersCommand }]
        arguments: [ @doctrine ]

    command.password.set:
        class: eTraxis\SimpleBus\Users\Handler\SetPasswordCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Users\SetPasswordCommand }]
        arguments: [ @logger, @doctrine, @etraxis.encoder ]
