checks:
    php:
        code_rating: true
        duplication: false

tools:
    external_code_coverage:
        timeout: 600
        runs: 4

filter:
    excluded_paths:
        - 'app/*'
        - 'src/AppBundle/DataFixtures/*'
        - 'tests/*'
        - 'web/*'
