checks:
    php:
        code_rating: true
        duplication: false

tools:
    external_code_coverage: true

filter:
    excluded_paths:
        - 'app/*'
        - 'src/AppBundle/DataFixtures/*'
        - 'tests/*'
        - 'web/*'
