exclude_patterns:
    - app/Resources/public/js/jquery-ui.js
    - web/app*.php

rules:

    # We have a lot of POST actions which respond with JSON and should not redirect anywhere.
    symfony.controller.missing_redirect_after_post:
        enabled: false
