language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
    - DB=mysql
    - DB=pgsql

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y php5-ldap

install:
    - cp app/config/travis.$DB.yml app/config/parameters.yml
    - composer install -n

before_script:
    - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - app/console --env=test --no-interaction doctrine:database:create
    - app/console --env=test --no-interaction doctrine:schema:create
    - app/console --env=test --no-interaction doctrine:fixtures:load --fixtures=src/AppBundle/DataFixtures/Tests

script:
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
