language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - DB=mysql
    - DB=pgsql

sudo: false

addons:
    apt:
        packages:
        - php5-ldap

before_install:
    - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - cp app/config/travis/parameters.$DB.yml app/config/parameters.yml
    - composer install -n

before_script:
    - app/console --env=test --no-interaction doctrine:database:create
    - app/console --env=test --no-interaction doctrine:schema:create
    - app/console --env=test --no-interaction doctrine:fixtures:load --fixtures=src/AppBundle/DataFixtures/Tests

script:
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
