language: php

php:
    - 5.4
    - 5.5
    - 5.6

install:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install -n

before_script:
    - app/console --env=test --no-interaction doctrine:database:create
    - app/console --env=test --no-interaction doctrine:schema:create

script:
    - phpunit
