services:

    command.export.csv:
        class: eTraxis\CommandBus\Shared\Handler\ExportToCsvCommandHandler
        tags: [{ name: nih_command_handler, command: eTraxis\CommandBus\Shared\ExportToCsvCommand }]
