services:

    command.user.register:
        class: eTraxis\SimpleBus\CommandHandler\User\RegisterUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Command\User\RegisterUserCommand }]
        arguments: [ @logger, @doctrine ]

    command.user.lock:
        class: eTraxis\SimpleBus\CommandHandler\User\LockUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Command\User\LockUserCommand }]
        arguments: [ @logger, @doctrine, %security_auth_attempts%, %security_lock_time% ]

    command.user.unlock:
        class: eTraxis\SimpleBus\CommandHandler\User\UnlockUserCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Command\User\UnlockUserCommand }]
        arguments: [ @logger, @doctrine ]

    command.user.index:
        class: eTraxis\SimpleBus\CommandHandler\User\ListUsersCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Command\User\ListUsersCommand }]
        arguments: [ @security.authorization_checker, @translator, @doctrine ]
