login_check:
    path: /login_check

logout:
    path: /logout

web:
    resource: "@AppBundle/Controller/Web/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AppBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin
