security:

    encoders:
        eTraxis\Entity\User:
            id: etraxis.encoder

    providers:
        etraxis_provider:
            id: etraxis.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern:    ^/
            form_login: ~
            logout:     ~
            anonymous:  ~
            simple_form:
                authenticator: ldap.authenticator
            remember_me:
                secret:   "%secret%"
                lifetime: 2592000
                path:     /
                domain:   ~

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
