imports:
    - { resource: services/ }
    - { resource: simplebus/ }

services:

    ldap:
        class: eTraxis\Service\LdapService
        arguments:
            - "@logger"
            - "%ldap_host%"
            - "%ldap_port%"
            - "%ldap_user%"
            - "%ldap_password%"
            - "%ldap_tls%"

    localizer:
        class: eTraxis\Service\LocalizerService
        arguments:
            - "@security.token_storage"
            - "%locale%"

    etraxis.mailer:
        class: eTraxis\Service\MailerService
        arguments:
            - "@logger"
            - "@twig"
            - "@mailer"

    etraxis.export:
        class: eTraxis\Service\ExportService

    etraxis.provider:
        class: eTraxis\Security\InternalUserProvider
        public: false
        arguments:
            - "@logger"
            - "@etraxis.repository.users"

    etraxis.encoder:
        class: eTraxis\Security\InternalPasswordEncoder
        public: false
        arguments:
            - "@translator"
            - "%password_min_length%"

    ldap.authenticator:
        class: eTraxis\Security\LdapAuthenticator
        public: false
        arguments:
            - "@logger"
            - "@command_bus"
            - "@ldap"
            - "%ldap_basedn%"
