services:

    etraxis.provider:
        class: eTraxis\Security\InternalUserProvider
        public: false
        arguments:
            - @logger
            - @doctrine

    etraxis.encoder:
        class: eTraxis\Security\InternalPasswordEncoder
        public: false

    etraxis.mailer:
        class: eTraxis\Service\MailerService
        arguments:
            - @logger
            - @twig
            - @mailer
