imports:
    - { resource: services/listeners.yml }
    - { resource: services/voters.yml }
    - { resource: commandbus/users.yml }
    - { resource: commandbus/groups.yml }
    - { resource: commandbus/projects.yml }

services:

    nih_command_bus:
        class: eTraxis\CommandBus\CommandBus
        arguments:
            - @service_container
            - @logger
            - @validator

    ldap:
        class: eTraxis\Service\LdapService
        arguments:
            - @logger
            - %ldap_host%
            - %ldap_port%
            - %ldap_user%
            - %ldap_password%
            - %ldap_tls%

    localizer:
        class: eTraxis\Service\LocalizerService
        arguments:
            - @security.token_storage
            - %locale%

    etraxis.mailer:
        class: eTraxis\Service\MailerService
        arguments:
            - @logger
            - @twig
            - @mailer

    etraxis.export:
        class: eTraxis\Service\ExportService

    etraxis.provider:
        class: eTraxis\Security\InternalUserProvider
        public: false
        arguments:
            - @logger
            - @doctrine

    etraxis.encoder:
        class: eTraxis\Security\InternalPasswordEncoder
        public: false
        arguments:
            - @translator
            - %password_min_length%

    ldap.authenticator:
        class: eTraxis\Security\LdapAuthenticator
        public: false
        arguments:
            - @logger
            - @nih_command_bus
            - @ldap
            - %ldap_basedn%
