imports:
    - { resource: simplebus/middleware.yml }
    - { resource: simplebus/users.yml }

services:

    ldap:
        class: eTraxis\Service\LdapService
        arguments:
            - @logger
            - %ldap_host%
            - %ldap_port%
            - %ldap_user%
            - %ldap_password%
            - %ldap_tls%

    etraxis.mailer:
        class: eTraxis\Service\MailerService
        arguments:
            - @logger
            - @twig
            - @mailer

    etraxis.provider:
        class: eTraxis\Security\InternalUserProvider
        public: false
        arguments:
            - @logger
            - @doctrine

    etraxis.encoder:
        class: eTraxis\Security\InternalPasswordEncoder
        public: false

    ldap.authenticator:
        class: eTraxis\Security\LdapAuthenticator
        public: false
        arguments:
            - @logger
            - @command_bus
            - @ldap
            - %ldap_basedn%

    etraxis.listener.authentication:
        class: AppBundle\EventListener\AuthenticationListener
        tags: [{ name: kernel.event_subscriber }]
        arguments:
            - @logger
            - @command_bus

    etraxis.listener.kernel:
        class: AppBundle\EventListener\KernelListener
        tags: [{ name: kernel.event_subscriber }]
        arguments:
            - @router
            - @translator
            - %locale%

    etraxis.listener.security:
        class: AppBundle\EventListener\SecurityListener
        tags: [{ name: kernel.event_subscriber }]
        arguments:
            - @session
