# Keep imports sorted alphabetically.
imports:
    - { resource: services/datatables.yml }
    - { resource: services/forms.yml }
    - { resource: services/listeners.yml }
    - { resource: services/repositories.yml }
    - { resource: services/voters.yml }
    - { resource: simplebus/command.field.yml }
    - { resource: simplebus/command.group.yml }
    - { resource: simplebus/command.project.yml }
    - { resource: simplebus/command.state.yml }
    - { resource: simplebus/command.template.yml }
    - { resource: simplebus/command.user.yml }
    - { resource: simplebus/middleware.yml }

services:

    ldap:
        class: eTraxis\Service\LdapService
        arguments:
            - "@logger"
            - "%ldap_host%"
            - "%ldap_port%"
            - "%ldap_user%"
            - "%ldap_password%"
            - "%ldap_tls%"

    localizer:
        class: eTraxis\Service\LocalizerService
        arguments:
            - "@security.token_storage"
            - "%locale%"

    etraxis.mailer:
        class: eTraxis\Service\MailerService
        arguments:
            - "@logger"
            - "@twig"
            - "@mailer"

    etraxis.export:
        class: eTraxis\Service\ExportService

    etraxis.provider:
        class: eTraxis\Security\InternalUserProvider
        public: false
        arguments:
            - "@logger"
            - "@etraxis.repository.users"

    etraxis.encoder:
        class: eTraxis\Security\InternalPasswordEncoder
        public: false
        arguments:
            - "@translator"
            - "%password_min_length%"

    ldap.authenticator:
        class: eTraxis\Security\LdapAuthenticator
        public: false
        arguments:
            - "@logger"
            - "@command_bus"
            - "@ldap"
            - "%ldap_basedn%"
