# Keep forms sorted alphabetically.
services:

    etraxis.form.appearance:
        class: eTraxis\Form\AppearanceForm
        tags: [{ name: form.type }]
        arguments: [ "@translator" ]

    etraxis.form.export:
        class: eTraxis\Form\ExportCsvForm
        tags: [{ name: form.type }]
        arguments: [ "@translator" ]

    etraxis.form.group:
        class: eTraxis\Form\GroupExForm
        tags: [{ name: form.type }]
        arguments: [ "@translator" ]

    etraxis.form.user:
        class: eTraxis\Form\UserForm
        tags: [{ name: form.type }]
        arguments: [ "@translator" ]
