# Keep listeners sorted alphabetically.
services:

    etraxis.listener.authentication:
        class: AppBundle\EventListener\AuthenticationListener
        tags: [{ name: kernel.event_subscriber }]
        arguments:
            - "@logger"
            - "@command_bus"

    etraxis.listener.kernel:
        class: AppBundle\EventListener\KernelListener
        tags: [{ name: kernel.event_subscriber }]
        arguments:
            - "@router"
            - "@translator"
            - "@security.authentication_utils"
            - "@security.authorization_checker"
            - "@security.token_storage"

    etraxis.listener.security:
        class: AppBundle\EventListener\SecurityListener
        tags: [{ name: kernel.event_subscriber }]
        arguments:
            - "@session"
