# Keep voters sorted alphabetically.
services:

    etraxis.voter.project:
        class: eTraxis\Voter\ProjectVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ @etraxis.repository.issues ]

    etraxis.voter.template:
        class: eTraxis\Voter\TemplateVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ @etraxis.repository.issues ]

    etraxis.voter.user:
        class: eTraxis\Voter\UserVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ @etraxis.repository.events, %password_expiration% ]
