# Keep voters sorted alphabetically.
services:

    etraxis.voter.list_item:
        class: eTraxis\Voter\ListItemVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ "@etraxis.repository.field_values" ]

    etraxis.voter.project:
        class: eTraxis\Voter\ProjectVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ "@etraxis.repository.issues" ]

    etraxis.voter.state:
        class: eTraxis\Voter\StateVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ "@etraxis.repository.events" ]

    etraxis.voter.template:
        class: eTraxis\Voter\TemplateVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ "@etraxis.repository.states", "@etraxis.repository.issues" ]

    etraxis.voter.user:
        class: eTraxis\Voter\UserVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ "@etraxis.repository.events", "%password_expiration%" ]
