# Keep voters sorted alphabetically.
services:

    etraxis.voter.project:
        class: eTraxis\Voter\ProjectVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ @doctrine ]

    etraxis.voter.user:
        class: eTraxis\Voter\UserVoter
        public: false
        tags: [{ name: security.voter }]
        arguments: [ @doctrine, %password_expiration% ]
